### ISSUE TITLE
error httplib.InvalidURL: nonnumeric 

### ISSUE THREAD

**Issue by h4ck1th4rd** [anonymousnm/tor-ddos#1]
mzaboss@DESKTOP-2PVC1UM ~/the-silencer/torshammer/tor-ddos
$ python torddos.py
entering tor entrence node
connected to tor nodes
connected to tor exit node
{
  "ip": "216.218.222.11"
}
[+] enter your target domain>>>> autoigs.com
http://autoigs.com
Traceback (most recent call last):
  File "torddos.py", line 19, in <module>
    ddos = httplib.HTTPConnection(target)
  File "/usr/lib/python2.7/httplib.py", line 751, in __init__
    (self.host, self.port) = self._get_hostport(host, port)
  File "/usr/lib/python2.7/httplib.py", line 792, in _get_hostport
    raise InvalidURL("nonnumeric port: '%s'" % host[i+1:])
httplib.InvalidURL: nonnumeric port: '//autoigs.com'

mzaboss@DESKTOP-2PVC1UM ~/the-silencer/torshammer/tor-ddos
$

**Comment by anonymousnm** [comment]
make sure you have https in there.

try https://www.autoigs.com
